[package]
edition = "2021"
name = "rust-and-cmake"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = {version = "0.15.6", features = ["rayon"]}
ndarray-stats = "0.5.1"

[build-dependencies]
cmake = "0.1.31"
